{Build} Dockerfile: update ubuntu from focal to jammy
Summary:
Recent update around how FMT is used is making our code needing a more version of FMT, we are updating here our Dockerfile build base image to work with the recent update.

- Ubuntu Focal comes with FMT v6.1.2 https://packages.ubuntu.com/focal/libfmt-dev
- Ubuntu Jammy comes with FMT v8.1.1 https://packages.ubuntu.com/jammy/libfmt-dev

Tested with Podman build `podman build . -t aria_data_tools`

- After modification:
```
COMMIT aria_data_tools
--> b67f4d5dfb72
Successfully tagged localhost/aria_data_tools:latest
```

- Before modification (error happens when compiling the Python Bindings)
```
/tmp/pip-req-build-8438o_l3/core/python/MpsPyBind.h:349:92:   required from here
  /usr/include/fmt/core.h:817:28: error: ‘struct fmt::v6::formatter<projectaria::tools::mps::StaticCameraCalibration>’ has no member named ‘parse’
You sent
 /usr/include/fmt/core.h:817:28: error: ‘struct fmt::v6::formatter<projectaria::tools::mps::OnlineCalibration>’ has no member named ‘parse’
```

Reviewed By: vijay609

Differential Revision: D48653506

fbshipit-source-id: 482dd32c73c816e1fd24ae44b8ad4aed321ead6d