{BugFix} Python - Aria Sensor Viewer - Fix web mode
Summary:
Fix the web mode (argument went missing)
```
"Aria Sensors Data Viewer", spawn=(not args.rrd_output_path and not args.web)
AttributeError: 'Namespace' object has no attribute 'web'
```

Reviewed By: PiotrBrzyski

Differential Revision: D77594981

fbshipit-source-id: bbbbcbe4529b9dc146b1c45754277c05d3deb671