{BugFix} Python - vrs_to_mp4 - Corner case with output filename
Summary:
Deal with cornercase if the output filename does not contain any folder part
` --output_video test.mp4`

- Program is failing, trying to create a folder from an empty string

I.e fixing an error of such type:
```
import os
os.makedirs("", exist_ok=True)

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    os.makedirs("", exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

** Process exited - Return Code: 1 **
Press Enter to exit terminal
```

- Fix some missing type annotation in some function declaration

Reviewed By: xiaqingp

Differential Revision: D60132567

fbshipit-source-id: ddf0eb3f8711a891d9afd3c904992b01b04f3e19